# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txtSendMsg = QtWidgets.QTextEdit(self.centralwidget)
        self.txtSendMsg.setGeometry(QtCore.QRect(0, 480, 651, 91))
        self.txtSendMsg.setObjectName("txtSendMsg")
        self.grpSnd = QtWidgets.QGroupBox(self.centralwidget)
        self.grpSnd.setGeometry(QtCore.QRect(660, 390, 141, 81))
        self.grpSnd.setTitle("")
        self.grpSnd.setObjectName("grpSnd")
        self.chkTimeSend = QtWidgets.QCheckBox(self.grpSnd)
        self.chkTimeSend.setGeometry(QtCore.QRect(10, 10, 71, 16))
        self.chkTimeSend.setObjectName("chkTimeSend")
        self.btnManualSend = QtWidgets.QPushButton(self.grpSnd)
        self.btnManualSend.setGeometry(QtCore.QRect(50, 40, 81, 31))
        self.btnManualSend.setObjectName("btnManualSend")
        self.linTimeNum = QtWidgets.QLineEdit(self.grpSnd)
        self.linTimeNum.setGeometry(QtCore.QRect(80, 8, 41, 20))
        self.linTimeNum.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.linTimeNum.setObjectName("linTimeNum")
        self.lblTimeNum = QtWidgets.QLabel(self.grpSnd)
        self.lblTimeNum.setGeometry(QtCore.QRect(125, 10, 54, 20))
        self.lblTimeNum.setObjectName("lblTimeNum")
        self.grpOpen = QtWidgets.QGroupBox(self.centralwidget)
        self.grpOpen.setGeometry(QtCore.QRect(660, 0, 141, 161))
        self.grpOpen.setTitle("")
        self.grpOpen.setObjectName("grpOpen")
        self.cmbParity = QtWidgets.QComboBox(self.grpOpen)
        self.cmbParity.setGeometry(QtCore.QRect(53, 130, 71, 22))
        self.cmbParity.setObjectName("cmbParity")
        self.cmbBaudrate = QtWidgets.QComboBox(self.grpOpen)
        self.cmbBaudrate.setGeometry(QtCore.QRect(53, 40, 71, 22))
        self.cmbBaudrate.setObjectName("cmbBaudrate")
        self.cmbPort = QtWidgets.QComboBox(self.grpOpen)
        self.cmbPort.setGeometry(QtCore.QRect(53, 10, 71, 22))
        self.cmbPort.setObjectName("cmbPort")
        self.cmbStopBits = QtWidgets.QComboBox(self.grpOpen)
        self.cmbStopBits.setGeometry(QtCore.QRect(53, 100, 71, 22))
        self.cmbStopBits.setObjectName("cmbStopBits")
        self.cmbByteSize = QtWidgets.QComboBox(self.grpOpen)
        self.cmbByteSize.setGeometry(QtCore.QRect(53, 70, 71, 22))
        self.cmbByteSize.setObjectName("cmbByteSize")
        self.lblPort = QtWidgets.QLabel(self.grpOpen)
        self.lblPort.setGeometry(QtCore.QRect(10, 15, 41, 16))
        self.lblPort.setObjectName("lblPort")
        self.lblBaudrate = QtWidgets.QLabel(self.grpOpen)
        self.lblBaudrate.setGeometry(QtCore.QRect(10, 45, 41, 16))
        self.lblBaudrate.setObjectName("lblBaudrate")
        self.lblByteSize = QtWidgets.QLabel(self.grpOpen)
        self.lblByteSize.setGeometry(QtCore.QRect(10, 75, 41, 16))
        self.lblByteSize.setObjectName("lblByteSize")
        self.lblStopBits = QtWidgets.QLabel(self.grpOpen)
        self.lblStopBits.setGeometry(QtCore.QRect(10, 105, 41, 16))
        self.lblStopBits.setObjectName("lblStopBits")
        self.lblVerifyBits = QtWidgets.QLabel(self.grpOpen)
        self.lblVerifyBits.setGeometry(QtCore.QRect(10, 135, 41, 16))
        self.lblVerifyBits.setObjectName("lblVerifyBits")
        self.txtRecvMsg = QtWidgets.QTextEdit(self.centralwidget)
        self.txtRecvMsg.setGeometry(QtCore.QRect(0, 0, 651, 471))
        self.txtRecvMsg.setObjectName("txtRecvMsg")
        self.btnOpenPort = QtWidgets.QPushButton(self.centralwidget)
        self.btnOpenPort.setGeometry(QtCore.QRect(710, 170, 81, 31))
        self.btnOpenPort.setObjectName("btnOpenPort")
        self.grpRcv = QtWidgets.QGroupBox(self.centralwidget)
        self.grpRcv.setGeometry(QtCore.QRect(660, 320, 141, 61))
        self.grpRcv.setTitle("")
        self.grpRcv.setObjectName("grpRcv")
        self.chkHexShow = QtWidgets.QCheckBox(self.grpRcv)
        self.chkHexShow.setGeometry(QtCore.QRect(10, 11, 91, 16))
        self.chkHexShow.setObjectName("chkHexShow")
        self.chkHexSend = QtWidgets.QCheckBox(self.grpRcv)
        self.chkHexSend.setGeometry(QtCore.QRect(10, 38, 91, 16))
        self.chkHexSend.setObjectName("chkHexSend")
        self.btnClearWin = QtWidgets.QPushButton(self.centralwidget)
        self.btnClearWin.setGeometry(QtCore.QRect(710, 220, 81, 31))
        self.btnClearWin.setObjectName("btnClearWin")
        self.btnSaveWin = QtWidgets.QPushButton(self.centralwidget)
        self.btnSaveWin.setGeometry(QtCore.QRect(710, 270, 81, 31))
        self.btnSaveWin.setObjectName("btnSaveWin")
        self.btnClose = QtWidgets.QPushButton(self.centralwidget)
        self.btnClose.setGeometry(QtCore.QRect(710, 530, 81, 31))
        self.btnClose.setObjectName("btnClose")
        self.lblRecvCnt = QtWidgets.QLabel(self.centralwidget)
        self.lblRecvCnt.setGeometry(QtCore.QRect(670, 480, 54, 12))
        self.lblRecvCnt.setObjectName("lblRecvCnt")
        self.lblSendCnt = QtWidgets.QLabel(self.centralwidget)
        self.lblSendCnt.setGeometry(QtCore.QRect(670, 500, 54, 12))
        self.lblSendCnt.setObjectName("lblSendCnt")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.chkTimeSend.setText(_translate("MainWindow", "定时发送"))
        self.btnManualSend.setText(_translate("MainWindow", "手动发送"))
        self.lblTimeNum.setText(_translate("MainWindow", "ms"))
        self.lblPort.setText(_translate("MainWindow", "串口号"))
        self.lblBaudrate.setText(_translate("MainWindow", "波特率"))
        self.lblByteSize.setText(_translate("MainWindow", "数据位"))
        self.lblStopBits.setText(_translate("MainWindow", "停止位"))
        self.lblVerifyBits.setText(_translate("MainWindow", "校验位"))
        self.btnOpenPort.setText(_translate("MainWindow", "打开串口"))
        self.chkHexShow.setText(_translate("MainWindow", "HEX格式显示"))
        self.chkHexSend.setText(_translate("MainWindow", "HEX格式发送"))
        self.btnClearWin.setText(_translate("MainWindow", "清除窗口"))
        self.btnSaveWin.setText(_translate("MainWindow", "保存窗口"))
        self.btnClose.setText(_translate("MainWindow", "关闭程序"))
        self.lblRecvCnt.setText(_translate("MainWindow", "TextLabel"))
        self.lblSendCnt.setText(_translate("MainWindow", "TextLabel"))

